### PR TITLE
Small contrib

### PR DESCRIPTION
**Pull request by jdlom**
Hi @avouacr,
tiny contrib.

By the way, what is the reason you decide to remove the toc ?
In my opinion, using toc improves the documentation in general.

### CODE REVIEW

**Comment by garronej** [comment]
thank you for the contribution, I'll let @avouacr review it.  

About the TOC. The link to the site in github was not the correct one.  
The site is served by GitBook: https://docs.sspcloud.fr/comment-contribuer-1/comment-contribuer

**Comment by garronej** [comment]
I think I get why @avouacr is using https://inseefrlab.github.io/docs.sspcloud.fr/docs/en/principles.html instead of https://docs.sspcloud.fr/onyxia-guide/decouverte-du-datalab, it's for enabling translation.  

@avouacr  It's not straight forward but translation can be enabled at the Gitbook level, I can show you or do it for you if you are interessted.  There would be different a branch by language.

**Comment by avouacr** [comment]
@jdlom We decided some time ago to make the [tutorials](https://www.sspcloud.fr/formation) section of the datalab the single entrypoint for documentation and tutorials, and as a result we removed the Documentation button. Since the organization of the tutorial page is already in chapters and only exposes HTML pages, I think the TOC is not useful anymore. But this could be discussed.

@garronej I saw that one could use GitBook to make translations, but from the documentation it was indeed not straightforward and a simple markdown documentation rendered by quarto was much easier to maintain, so we transitioned a while back. I think we should devote future efforts to improve the documentation rather than reverting to GitBook

**Comment by garronej** [comment]
Makes sense !

**Comment by jdlom** [comment]
I think some chapters are big and the TOC would be useful, especially if you want to quickly go to a specific part of the tutorial. For the moment, you have to scroll down.

**Comment by garronej** [comment]
@avouacr Yes, no problem, I'll let you be the judge of that. I just thought there was some confusion since I didn't follow the move to Quarto.
Just a suggestion, but perhaps https://docsify.js.org/ would be a good fit for this use case. It's a website generator from markdown files, but with no build step! It's 100% on the frontend, offering the benefits of a search bar, a table of contents, and internationalization, while being much lighter and more sovereign than GitBook.

**Pull request merged**
